### ISSUE TITLE
Publish via CI

### ISSUE THREAD

**Issue by scothis** [projectriff/chocolatey#5]
Requiring a human to publish updates is fragile. We can have an action do that for us.

**Comment by fbiville** [comment]
The only "non-trivial" change is the required version of Kubernetes (CLI).

**Comment by scothis** [comment]
> The only "non-trivial" change is the required version of Kubernetes (CLI). 

Why? The riff cli doesn't depend on kubectl

**Comment by fbiville** [comment]
It does not, but in the same spirit as Homebrew, that's the way the dependency to Kubernetes is encoded.

**Comment by trisberg** [comment]
Could we just remove that dependency? All we need is a kube config file and we will show an error if one isn't found.

**Comment by fbiville** [comment]
I think we could for Chocolatey but a similar PR for Homebrew would be rejected.

**Comment by fbiville** [comment]
Actually, reviewing the initial [Homebrew PR](https://github.com/Homebrew/homebrew-core/pull/37101), the dependency to K8s CLI was actually required at the time (not because of riff depending on K8s in general but because of the actual shellout to kubectl). 

So we may actually be able to remove that dependency from both recipes.
